trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
- script: |
    pip install -r "Lession 06 - Azure Functions/source/requirements.txt"
    pytest -q "Lession 06 - Azure Functions/source/tests"
  displayName: 'Run tests'
