trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
- script: |
    pip install -r source/requirements.txt
    pytest -q
  displayName: 'Run tests'
